optimizer: 'SGD'
dataset: 'wikic/base'
num_sample: 1
weight_decay: 0.0001
lr: 0.001
epochs: 300
batch_size: 128
batch_log_interval: 50
train_limit: 500_000
lamda: 0.9
experiment: 
  name: 'supervised'
  n_exp: 1
  n_trials: 1
  feedback: 'supervised'
  regularizers: null
  labeled_portion: u0
